on:
  push:
    branches:
      - master

jobs:
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: log to npmjs
        run: npx npm-cli-login -u loriick -p "${{secrets.NPMJS_PASSWORD}}" -e loricktravailleur@gmail.com
      - name: publish to npm
        run: npm publish
